# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions


name: main

on: 
  push:
    branches:
      - main 

jobs: 

# run tests for lambda handler 

# build terraform infra 

