# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions


name: main

on: 
  push:
    branches:
      - main 

jobs: 

# run tests for lambda handler 

# build terraform infra 

# upload s3 resources  


  deploy-site:
    #needs: build-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: www.oabcloudresumechallenge.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: /website


# invalidate cloudfront cache


  invalidate-cloudfront:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: './'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}